### ISSUE TITLE
Does not seem to work with NC 13

### ISSUE THREAD

**Issue by rucksman** [newroco/W2G2#6]
I just installed this app in nextcloud 13 as the workin2gether app does not seem to be available in naxtcloud 13.

Another user in a group folger marked the file as locked, but I was able to open it via the nextcloud app on a windowd pc, make changes and save it again. So obvioulsy the file was NOT locked.

I also do not understand your advice, because there is no table oc_locks_w2g in my database.:
````After installing W2G2, enter this command in DB:
insert into oc_locks_w2g2 select * from oc_locks_w2g;

**Comment by Emi94** [comment]
W2G2 works only on the Nextcloud interface. For it to work with the sync client too, would most likely require changes to the desktop client, which we do not control.

That command is for migrating locks from Working2gether to W2G2, where oc_locks_w2g is the table used by Working2gether and oc_locks_w2g2 is the one used by W2G2. If you don't have table oc_locks_w2g you either never had Working2gether installed or you deleted the app before doing the migration (although in my case the table is still available after deleting the app).

**Comment by putt1ck** [comment]
NB you cannot universalise locks because (a) different apps deal with locks differently (b) so do different file systems - moreover people can take files away from a system in many ways (email, USB, filesharing services), so this is not an NC problem, it's a human problem.

W2G2 is an aid to collaboration - it lets users tell other users (asynchronously and one-to-all) that a file is being changed. But it still requires those other users to play their part in the system.
