### ISSUE TITLE
Cannot enable W2G2: "Error: This app can not be enabled because it makes the server unstable"

### ISSUE THREAD

**Issue by DidierTrosset-Acqiris** [newroco/W2G2#8]
With nextcloud version 13.0.0, I cannot enable W2G2.

I tried first to enable the module directly from the nextcloud Apps browser. It shows: "Error: This app can not be enabled because it makes the server unstable"

I then downloaded the w2g2-1.0.0.tar.gz package, and installed manually in nextcloud/apps. When clicking the *Enable* button of **W2G2** in the *Your Apps* admin page, same: "Error: This app can not be enabled because it makes the server unstable"

Thanks for any help.

**Comment by DidierTrosset-Acqiris** [comment]
nextcloud/data/nextcloud.log shows the following:
\"Message\":\"An exception occurred while executing 'CREATE table oc_locks_w2g2(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255))':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes\",\"Code\":0

**Comment by DidierTrosset-Acqiris** [comment]
I changed the SQL string in w2g2/appinfo/app.php to:
"CREATE table *PREFIX*" . app::table . "(name varchar(191) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(191))"

Changing the 255 to 191, guessing 255 was too large.

It looks better. I can start W2G2, and lock files.

Could anyone tell whether this is a good thing or not?

**Comment by Patt92** [comment]
Actually yes, originally it was planned to create varchar(255) name as text variable.
I simply used varchar, because we had a windows server before... It should be made an id field as primary key containing either the fileid of the filecache combined with i.e. the path hash of given element, for preventing false locks after a filecache cleanup. Never checked, if a fileid is gonna used again after the old file gets deleted. We have way too much files.

I'd keep it in mind @newroco

**Comment by ExaconAT** [comment]
Please make an update, we have the same problem @ NC13

**Comment by orzuionut** [comment]
Fixed.

**Comment by paulcalabro** [comment]
@orzuionut I'm experiencing a similar issue with Nextcloud 17 and the latest version of the app. Once I enable this app, I start to see "Connection to server lost" error messages in the top-right corner.
